runtime: nodejs20
env: standard
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

env_variables:
  NODE_ENV: 'production'
  DATABASE_URL: 'postgresql://postgres:mysecretpassword@34.132.206.96:5432/pdfextractor_db'

entrypoint: npm run start

handlers:
  - url: /invoices/download/(.*)
    static_files: src/faturas/\1
    upload: src/faturas/(.*)
